### PR TITLE
Added databases/php71-{dba,interbase,mysqli,odbc,pdo_dblib,pdo_firebi…

### PR DESCRIPTION
**Pull request by Nimloth**
…rd,pdo_mysql,pdo_sqlite,sqlite3}

### CODE REVIEW

**Comment by t-zuehlsdorff** [comment]
@Nimloth 
Do the pdo-* extensions really work for you? I created them already by myself, but got an error:

```
# cd /usr/ports/databases/php71-pdo_firebird/
root@gitlab:/usr/ports/databases/php71-pdo_firebird # make clean && make install
===>  Cleaning for php71-pdo_firebird-7.1.0RC5
Unknown extension pdo for PHP 71.
*** Error code 1

Stop.
make: stopped in /usr/ports/databases/php71-pdo_firebird

```

**Comment by Nimloth** [comment]
All the ports I created a pull request for ran without problem through poudriere. E.g.
poudriere bulk -j testing databases/php71-pdo_firebird
reported no errors.

I just bulk-compiled these two and that worked, as well.
poudriere bulk -j testing databases/php71-pdo_firebird
and
poudriere bulk -j testing databases/php71-pdo
built the desired packages just fine.

Do you use a clean jail for your builds? If not, maybe some settings in your make.conf cause problems?

**Comment by Nimloth** [comment]
sorry - just clicked close and comment instead of just comment, so I had to reopen... ;-)

**Comment by t-zuehlsdorff** [comment]
Sorry it took so long. It seems to work now. :) But your pull request has a conflict. Could you please resolve it? I will work further on PHP 7.1 next week :)

**Comment by Nimloth** [comment]
No worries - I fixed the conflicts (I am a n00b where git is concerned). Auto-merge should work now.

**Pull request merged**
